desirated_framerate: 60
display_shell_interface: false
is_zmq_api_enabled: true
is_serial_enabled: false
color_schemes:
  - - red
    - green
    - blue
  - - '#2a04ff'
    - '#ff9604'
  - - '#02e6ff'
    - '#ff4a02'
  - - '#2bff01'
    - '#ff0127'
  - - '#fff700'
    - '#f700ff'
  - - '#ee00ac'
    - blue
  - - red
  - - green
  - - blue
  - - yellow
  - - pink
  - - '#ee00ac'
    - blue
audio_ports:
  - max_frequency: 12000
    min_frequency: 200
    min_volume_threshold: 1.0e-07
    n_rolling_history: 4
    name: Built-in Microphone
    number_of_audio_samples: 24
    sampling_rate: 44000
  - max_frequency: 12000
    min_frequency: 200
    min_volume_threshold: 1.0e-07
    n_rolling_history: 4
    name: Loopback Audio
    number_of_audio_samples: 24
    sampling_rate: 44000
strips:
  - name: Angles
    serial_port_name: /dev/tty.usbserial-A50285BI
    active_state_index: 2
    is_online: false
    midi_ports_for_changing_mode:
      - Audio2Led ChangeMod Center
    midi_ports_for_visualization:
      - Audio2Led Drum
      - Audio2Led Synth
    original_physical_shape:
      - 34
      - 52
      - 50
    midi_range:
      - 48
      - 50
    scene:
      backgrounds:
        - svg_string:
            M50.000169,0 C77.5959091,0 100,22.4040909 100,49.999831 C100,77.5955712
            77.5959091,100 50.000169,100 C22.4044288,100 0,77.5955712 0,49.999831 C0,22.4040909
            22.4044288,0 50.000169,0 Z
      shapes:
        - offset:
            - 0
            - 0
          pixel_range:
            - 86
            - 136
          svg_string:
            M50.000169,0 C77.5959091,0 100,22.4040909 100,49.999831 C100,77.5955712
            77.5959091,100 50.000169,100 C22.4044288,100 0,77.5955712 0,49.999831 C0,22.4040909
            22.4044288,0 50.000169,0 Z
        - offset:
            - 0
            - 0
          pixel_range:
            - 34
            - 86
          svg_string:
            M186.813356,0 C214.409096,0 236.813187,22.4040909 236.813187,49.999831
            C236.813187,77.5955712 214.409096,100 186.813356,100 C159.217616,100 136.813187,77.5955712
            136.813187,49.999831 C136.813187,22.4040909 159.217616,0 186.813356,0 Z
        - offset:
            - 0
            - 0
          pixel_range:
            - 0
            - 34
          svg_string:
            M323.626543,0 C351.222283,0 373.626374,22.4040909 373.626374,49.999831
            C373.626374,77.5955712 351.222283,100 323.626543,100 C296.030802,100 273.626374,77.5955712
            273.626374,49.999831 C273.626374,22.4040909 296.030802,0 323.626543,0 Z
      size:
        height: 175
        scale: 1
        width: 305
    states:
      - name: midi-scroll-shape
        active_visualizer_effect: piano_echo
        active_color_scheme_index: 10
        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 500
        chunk_size: 5
        blur_value: 14.2
        is_reverse: false
        is_mirror: true
      - name: midi-scroll-shape-slow
        active_visualizer_effect: piano_echo
        active_color_scheme_index: 10
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 1
        chunk_size: 5
        blur_value: 0.1
        is_reverse: false
        is_mirror: true
      - name: test
        active_visualizer_effect: piano_echo
        active_color_scheme_index: 10
        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 215
        chunk_size: 2
        blur_value: 14.2
        is_reverse: false
        is_mirror: false
