desirated_framerate: 60
display_shell_interface: false
is_zmq_api_enabled: true
is_serial_enabled: false
color_schemes:
  - - red
    - green
    - blue
  - - red
  - - green
  - - blue
  - - '#2a04ff'
    - '#ff9604'
  - - '#02e6ff'
    - '#ff4a02'
  - - '#2bff01'
    - '#ff0127'
  - - '#fff700'
    - '#f700ff'
  - - '#ee00ac'
    - blue
audio_ports:
  - max_frequency: 12000
    min_frequency: 200
    min_volume_threshold: 1.0e-07
    n_rolling_history: 4
    name: Built-in Microphone
    number_of_audio_samples: 24
    sampling_rate: 44000
  - max_frequency: 12000
    min_frequency: 200
    min_volume_threshold: 1.0e-07
    n_rolling_history: 4
    name: Loopback Audio
    number_of_audio_samples: 24
    sampling_rate: 44000
strips:
  - name: Maven
    serial_port_name: /dev/tty.usbserial-A50285BI
    active_state_index: 1
    is_online: false
    midi_ports_for_changing_mode:
      - Audio2Led ChangeMod TopBar
    midi_ports_for_visualization:
      - Audio2Led Synth
    original_physical_shape:
      - 50
      - 50
      - 50
      - 50
      - 50
      - 50
      - 50
      - 50
      - 50
      - 50
      - 50
      - 50
      - 50
      - 50
    midi_range:
      - 47
      - 74
    scene:
      shapes:
        - offset:
            - 0
            - 15
          pixel_range:
            - 0
            - 50
          svg_string: M1 390.922V82.832
        - offset:
            - 0
            - 30
          pixel_range:
            - 50
            - 100
          svg_string: M24.4401 389.922V36.555
        - offset:
            - 0
            - 45
          pixel_range:
            - 100
            - 150
          svg_string: M48.8803 389.922V14.865
        - offset:
            - 0
            - 60
          pixel_range:
            - 150
            - 200
          svg_string: M73.3204 389.922V3.036
        - offset:
            - 0
            - 75
          pixel_range:
            - 200
            - 250
          svg_string: M97.7605 389.922V0
        - offset:
            - 0
            - 90
          pixel_range:
            - 250
            - 300
          svg_string: M122.201 389.922V6.295
        - offset:
            - 0
            - 105
          pixel_range:
            - 300
            - 350
          svg_string: M146.641 389.922V15.512
        - offset:
            - 0
            - 120
          pixel_range:
            - 350
            - 400
          svg_string: M171.081 389.922V36.928
        - offset:
            - 0
            - 135
          pixel_range:
            - 400
            - 450
          svg_string: M195.521 389.922V70.343
        - offset:
            - 0
            - 150
          pixel_range:
            - 450
            - 500
          svg_string: M219.961 389.922V165.043
        - offset:
            - 0
            - 150
          pixel_range:
            - 500
            - 550
          svg_string: M244.401 389.922V186.05
        - offset:
            - 0
            - 150
          pixel_range:
            - 550
            - 600
          svg_string: M268.841 389.922v-191.66
        - offset:
            - 0
            - 150
          pixel_range:
            - 600
            - 650
          svg_string: M293.282 389.922V208.274
        - offset:
            - 0
            - 150
          pixel_range:
            - 650
            - 700
          svg_string: M317.722 389.922V230.914
      size:
        width: 300
        height: 180
        scale: 1
    states:
      - name: audio-intensity
        active_visualizer_effect: channel_intensity
        active_color_scheme_index: 4
        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 0.1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 484
        chunk_size: 5
        blur_value: 0.1
        is_reverse: false
        is_mirror: false
      - name: midi-scroll-shape-slow
        active_visualizer_effect: piano_echo
        active_color_scheme_index: 4
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 142
        time_interval: 120
        chunk_size: 20
        blur_value: 0.1
        is_reverse: false
        is_mirror: false
      - name: midi-scroll-shape-fast
        active_visualizer_effect: piano_echo
        active_color_scheme_index: 0
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 500
        chunk_size: 5
        blur_value: 10.2
        is_reverse: false
        is_mirror: false
      - name: midi-scroll
        active_visualizer_effect: piano_scroll
        active_color_scheme_index: 5
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 1
        chunk_size: 19
        blur_value: 0.1
        is_reverse: false
        is_mirror: false
      - name: time-alt-chunk
        active_visualizer_effect: alternate_color_chunks
        active_color_scheme_index: 5
        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 500
        chunk_size: 20
        blur_value: 5.6
        is_reverse: false
        is_mirror: false
      - name: generic-fire
        active_visualizer_effect: fire
        active_color_scheme_index: 0
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 120
        chunk_size: 5
        blur_value: 3.3
        is_reverse: false
        is_mirror: false
  - name: Maven2
    serial_port_name: /dev/tty.usbserial-A50285BI2
    active_state_index: 0
    is_online: false
    midi_ports_for_changing_mode:
      - Audio2Led ChangeMod Center
    midi_ports_for_visualization:
      - Audio2Led Synth
    original_physical_shape:
      - 72
    midi_range:
      - 47
      - 74
    scene:
      shapes:
        - offset:
            - 0
            - 15
          pixel_range:
            - 0
            - 72
          svg_string: M-5,400 T325,400
      size:
        width: 300
        height: 180
        scale: 1
    states:
      - name: audio-intensity
        active_visualizer_effect: channel_intensity
        active_color_scheme_index: 1
        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 0.1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 484
        chunk_size: 5
        blur_value: 0.1
        is_reverse: false
        is_mirror: true
      - name: midi-scroll-shape-slow
        active_visualizer_effect: piano_echo
        active_color_scheme_index: 3
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 142
        time_interval: 120
        chunk_size: 20
        blur_value: 0.1
        is_reverse: false
        is_mirror: false
      - name: midi-scroll
        active_visualizer_effect: piano_scroll
        active_color_scheme_index: 5
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 1
        chunk_size: 19
        blur_value: 0.1
        is_reverse: false
        is_mirror: false
      - name: time-alt-chunk
        active_visualizer_effect: alternate_color_chunks
        active_color_scheme_index: 5
        active_audio_channel_index: 1
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 500
        chunk_size: 20
        blur_value: 5.6
        is_reverse: false
        is_mirror: false
      - name: generic-fire
        active_visualizer_effect: fire
        active_color_scheme_index: 0
        active_audio_channel_index: 0
        audio_samples_filter_min: 0
        audio_samples_filter_max: 24
        audio_gain: 1
        audio_decay: 0.1
        division_value: 0
        max_brightness: 255
        time_interval: 120
        chunk_size: 5
        blur_value: 3.3
        is_reverse: false
        is_mirror: false
