desirated_framerate: 60
display_shell_interface: false
is_zmq_api_enabled: true
is_serial_enabled: false
color_schemes:
- - red
  - green
  - blue
- - '#2a04ff'
  - '#ff9604'
- - '#02e6ff'
  - '#ff4a02'
- - '#2bff01'
  - '#ff0127'
- - '#fff700'
  - '#f700ff'
- - red
- - green
- - blue
- - yellow
- - pink
- - '#ee00ac'
  - blue
audio_ports:
- max_frequency: 12000
  min_frequency: 200
  min_volume_threshold: 1.0e-07
  n_rolling_history: 4
  name: Built-in Microphone
  number_of_audio_samples: 24
  sampling_rate: 44000
- max_frequency: 12000
  min_frequency: 200
  min_volume_threshold: 1.0e-07
  n_rolling_history: 4
  name: Loopback Audio
  number_of_audio_samples: 24
  sampling_rate: 44000
strips:
- name: Maven
  serial_port_name: /dev/tty.usbserial-A50285BI
  active_state_index: 0
  is_online: false
  midi_ports_for_changing_mode:
  - Audio2Led ChangeMod TopBar
  midi_ports_for_visualization:
  - Audio2Led Synth
  original_physical_shape:
  - 50
  - 50
  - 50
  - 50
  - 50
  - 50
  - 50
  - 50
  - 50
  - 50
  midi_range:
  - 47
  - 73
  scene:
    shapes:
    - offset:
      - 0
      - 15
      pixel_range:
      - 0
      - 50
      svg_string: M0,0 T0,150
    - offset:
      - 0
      - 30
      pixel_range:
      - 50
      - 100
      svg_string: M50,0 T50,150
    - offset:
      - 0
      - 45
      pixel_range:
      - 100
      - 150
      svg_string: M100,0 T100,150
    - offset:
      - 0
      - 60
      pixel_range:
      - 150
      - 200
      svg_string: M150,0 T150,150
    - offset:
      - 0
      - 75
      pixel_range:
      - 200
      - 250
      svg_string: M200,0 T200,150
    - offset:
      - 0
      - 90
      pixel_range:
      - 250
      - 300
      svg_string: M250,0 T250,150
    - offset:
      - 0
      - 105
      pixel_range:
      - 300
      - 350
      svg_string: M300,0 T300,150
    - offset:
      - 0
      - 120
      pixel_range:
      - 350
      - 400
      svg_string: M350,0 T350,150
    - offset:
      - 0
      - 135
      pixel_range:
      - 400
      - 450
      svg_string: M400,0 T400,150
    - offset:
      - 0
      - 150
      pixel_range:
      - 450
      - 500
      svg_string: M450,0 T450,150
    size:
      width: 300
      height: 180
      scale: 1
  states:
  - name: Spectrum
    active_visualizer_effect: channel_flash
    active_color_scheme_index: 0
    active_audio_channel_index: 1
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 0.7
    audio_decay: 0.001
    division_value: 0
    max_brightness: 255
    time_interval: 500
    chunk_size: 23
    blur_value: 0.1
    is_reverse: false
    is_mirror: false
  - name: test2
    active_visualizer_effect: piano_echo
    active_color_scheme_index: 0
    active_audio_channel_index: 1
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 0.6
    audio_decay: 0.05
    division_value: 0
    max_brightness: 255
    time_interval: 72
    chunk_size: 29
    blur_value: 0.2
    is_reverse: false
    is_mirror: false
