desirated_framerate: 60
display_shell_interface: false
is_zmq_api_enabled: true
color_schemes:
- - red
  - green
  - blue
- - '#2a04ff'
  - '#ff9604'
- - '#02e6ff'
  - '#ff4a02'
- - '#2bff01'
  - '#ff0127'
- - '#fff700'
  - '#f700ff'
- - red
- - green
- - blue
- - yellow
- - pink
- - '#ee00ac'
  - blue
audio_ports:
- max_frequency: 12000
  min_frequency: 200
  min_volume_threshold: 1.0e-07
  n_rolling_history: 4
  name: Built-in Microphone
  number_of_audio_samples: 24
  sampling_rate: 44000
- max_frequency: 12000
  min_frequency: 200
  min_volume_threshold: 1.0e-07
  n_rolling_history: 4
  name: Loopback Audio
  number_of_audio_samples: 24
  sampling_rate: 44000
strips:
- name: Top Bar
  serial_port_name: /dev/tty.usbserial-A50285BI
  active_state_index: 0
  is_online: false
  midi_ports_for_changing_mode:
  - Audio2Led ChangeMod TopBar
  midi_ports_for_visualization:
  - LPK25
  - Audio2Led Synth
  original_physical_shape:
  - 80
  scene:
    shapes:
    - offset:
      - 0
      - -100
      pixel_range:
      - 0
      - 80
      svg_string: M0,-10 T300,-10
    size:
      width: 300
      height: 10
      scale: 1.2
  states:
  - name: Forevermore
    active_visualizer_effect: alternate_color_chunks
    active_color_scheme_index: 4
    active_audio_channel_index: 1
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24
    audio_gain: 0.1
    audio_decay: 0.5
    division_value: 0
    max_brightness: 55
    time_interval: 0
    chunk_size: 37
    blur_value: 8.0
    is_reverse: false
    is_mirror: true
